### ISSUE TITLE
Manual editing of photos in database

### ISSUE THREAD

**Issue by xevenheaven** [spinningarrow/kudos#11]
We need to get better res photos. T_T

**Comment by spinningarrow** [comment]
Is there anything left for the photo editing, or can we close this? (not counting taking the photos as part of this issue :stuck_out_tongue:)

**Comment by xevenheaven** [comment]
If you're not counting the ones we haven't taken then this is done.

**Comment by spinningarrow** [comment]
Wow, you reply fast!
All righty, let's close this! I LOVE CLOSING ISSUES!

**Comment by xevenheaven** [comment]
All I had to do was reply to the email!

CLOSE CLOSE CLOSE ALLLLLLL OF THEM!!!! 😁

**Comment by spinningarrow** [comment]
Once you see the open PR when you have the time (PR #20), we'll get to close another two issues! :grin:
