### ISSUE TITLE
Make graph a React component

### ISSUE THREAD

**Issue by xevenheaven** [spinningarrow/kudos#12]
Is this a good idea?

**Comment by spinningarrow** [comment]
So I think this is a good idea because it makes it easier for us to implement the toggling of the sidebar (`KudosBox`) and also getting the data into the graph.

**Comment by spinningarrow** [comment]
I've created a really quick and dirty wrapper as part of #8 to get things working for now – we can improve this later and see if we need the react-d3 component we saw online.
