### ISSUE TITLE
(Re)naming things

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/kudos#15]
Trying to solve one of the [two hard problems in Computer Science](http://martinfowler.com/bliki/TwoHardThings.html) 😜

@xevenheaven: Does this sound okay? All suggestions welcome!

```
- App ('KudosApp' currently)
    - LoginForm
    - UsersGraph ('TeamGraph' currently)
    - ProfileBox ('CurrentUserBox' currently)
    - KudosBox
      - KudosForm
        - KudosList
            - KudosItem ('Kudo', currently which sounds… weird)
```

**Comment by xevenheaven** [comment]
Just wondering if there's a need for Login_Form_ and Profile_Box_, or just Login and Profile will do. UsersGraph still sound funny. :tongue: Users? Graph? Network? Web? Team? Squad? Partyyyy! (You know I'm just throwing out random words! :joy:)

**Comment by spinningarrow** [comment]
Haha :grin: 

I was thinking that since they're names of components, maybe they should be nouns (this is for 'Login')? What do you think?

And you pinpointed the 3 that even I don't really like! :tongue:

I'm okay with Profile for now, but I thought in the future we might have an actual profile (if we go down the 'achievements', 'activities', etc route). 'ProfileBox' isn't the best name either though, I agree.

UsersGraph… I dunno. Something to do with 'visualization'? Visual? 'Users' is not too bad. 'People'? Back to 'TeamGraph'?

**Comment by spinningarrow** [comment]
v1

```
- App
    - LoginForm
    - Team
    - CommandCenter
    - KudosBox
      - KudosForm
        - KudosList
            - KudosNote
```

**Comment by spinningarrow** [comment]
v2

```
- App
    - LoginStation
    - TeamDepot
    - CommandCenter
    - KudosBase
      - KudosForm
        - KudosList
            - KudosNote
```

**Comment by xevenheaven** [comment]
:+1:

**Comment by spinningarrow** [comment]
vFinal

```
- App
    - LoginStation
    - TeamHub
    - CommandCenter
    - KudosBase
      - KudosForm
        - KudosList
            - KudosNote
```

**Comment by xevenheaven** [comment]
:+1: :+1:
