### ISSUE TITLE
Create team images for nodes

### ISSUE THREAD

**Issue by xevenheaven** [spinningarrow/kudos#26]
Instead of having a normal solid fill circle, have customised team circular images as the parent nodes.
- Removes dependencies on colorbrewer
- Removes functions like `color()`

**Comment by spinningarrow** [comment]
What kind of images do you have in mind?

**Comment by xevenheaven** [comment]
Well, at least for now, I'm just going with something simple for the first release. (Basically, a coloured circle with the team name, lol.) Colour scheme should follow what we had previously.

D'you have any recommendations?

**Comment by spinningarrow** [comment]
This might be a stupid question, but in that case why don't we use `circle`s for those? Does that add more complications? The `append` method can take in a function, so we can create `image` nodes for the leaves and `circle` nodes for the others.

**Comment by xevenheaven** [comment]
If you mean using `svg:circle`, then yes, it totally adds more complications. (Because I have already tried doing that last Friday.) The `append` causes issues with the node reference, etc etc etc. Which is why this became a solution instead - using _all_ images (_all_ circles, or _all_ whatever) for simplicity's sake. (Or maybe I'm just too stupid to figure a workaround for it, but you could try. :tongue:)

**Comment by spinningarrow** [comment]
Nah, it's okay, I was just asking :tongue:
