### ISSUE TITLE
Kudos count doesn't always update in graph

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/kudos#3]
Seems to be happening when a kudo is created from another session for that user (node animates but count doesn't increase).

**Comment by spinningarrow** [comment]
@xevenheaven I think we don't care about this one any more, do we? Since we're planning to do away with the counts next to the user's name on the graph.

**Comment by xevenheaven** [comment]
Yeah, the count next to the user's name is ugly. Don't think this issue is relevant already then.

**Comment by spinningarrow** [comment]
All righty, closing this!
