### ISSUE TITLE
Support emoticons

### ISSUE THREAD

**Issue by xevenheaven** [spinningarrow/kudos#31]
A nice to have - to spice up the kudos.

**Comment by spinningarrow** [comment]
Ooh, good idea!

**Comment by xevenheaven** [comment]
This is pretty interesting - http://os.alfajango.com/css-emoticons/ (but they look pretty ugly, so no. Hahaha.)

**Comment by xevenheaven** [comment]
Will this be an overkill? https://github.com/ritz078/embed.js

**Comment by spinningarrow** [comment]
https://github.com/twitter/twemoji ?

**Comment by spinningarrow** [comment]
http://ellekasai.github.io/twemoji-awesome/
