### ISSUE TITLE
ES6ify ALL the things!

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/kudos#7]

**Comment by xevenheaven** [comment]
WHY ME! O_O

**Comment by spinningarrow** [comment]
Haha just for fun! ⚡️ We're gonna do it together anyway 😛

**Comment by xevenheaven** [comment]
Hahahaha okok. Kudos! :D

**Comment by spinningarrow** [comment]
So ES6. Much fun. Wow. https://babeljs.io/
I'm using `reactify` in the code for #8 - looks like Babel supports JSX compilation and has a browserify transformer; let's look into using that. Or not.

// I'm putting this down here because I'm half certain I'll forget all this by tomorrow.

**Comment by spinningarrow** [comment]
Oh and http://tagtree.io/courses/expert-es6/do

**Comment by spinningarrow** [comment]
So turns out that "Babel" is pronounced "babble".
