### ISSUE TITLE
Upgrade to Deployd 0.8.0

### ISSUE THREAD

**Issue by spinningarrow** [spinningarrow/kudos#9]
Apparently [it's out](https://github.com/deployd/deployd/blob/master/HISTORY.md) and [active development has resumed](https://gist.github.com/NicolasRitouet/fde7e991e2e162412526).

**Comment by xevenheaven** [comment]
So is this Deployd compatible with Windows? Or is this the same one you're using?

**Comment by spinningarrow** [comment]
The one I was using was 0.7.0; the one you had was 0.6.1. Not sure about Windows compatibility :confused:

**Comment by spinningarrow** [comment]
Ooh, [they've upgraded the Windows installer to 0.7.0](https://github.com/deployd/deployd#install-on-windows)! You can use that for now, and we can try building the 0.8.0 version from source later. It's not that urgent I'd say.

**Comment by spinningarrow** [comment]
Btw, the server is already using 0.8.0 so we'll just see how it goes and take note of any unexpected errors. I don't _think_ there were any changes in the APIs we were using.

**Comment by spinningarrow** [comment]
This is working fine so I'm closing it.
